project:
  type: website

website:
  title: "Vanny Chen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: research.qmd
      - text: Research
      - projects.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

